name = "ytsruh"
compatibility_date = "2025-07-08"

routes = [{ pattern = "www.ytsruh.com", custom_domain = true }]
workers_dev = false
preview_urls = false

[assets]
not_found_handling = "single-page-application"
directory = "./build/client" 
